### ISSUE TITLE
Github Languages not detecting Tsx files

### ISSUE THREAD

**Issue by JawHawk** [JawHawk/Anichinu#10]
![image](https://github.com/JawHawk/Anichinu/assets/86140365/ea91331d-2f4c-4a0f-ba4e-3525f26e91e5)

The repo consists of tsx files, but not detected

**Comment by shreyass-ranganatha** [comment]
[GitHub Repository Languages Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-languages)

and the REST API fetch for your repo's language content:
![image](https://github.com/JawHawk/Anichinu/assets/94926409/be81521e-2c80-4364-9167-44da636dd34f)

Which gives Javascript a whopping 99.3041022 % score.. so- it makes sense for TSX not showing up

**Comment by JawHawk** [comment]
Ohh, I think that is mainly because of the build folder also being pushed. If put in .gitignore, still it appears because of git cache. Can you try removing that if possible  @shreyass-ranganatha ?

**Comment by mukeshmx** [comment]
Hey @JawHawk we have fixed this issue and opened a PR

**Comment by JawHawk** [comment]
@mukeshmx Yes, will check it up soon

**Comment by mukeshmx** [comment]
Thank you, please try and review it before 31st midnight :) @JawHawk
