### ISSUE TITLE
Redirecting user to wrong link

### ISSUE THREAD

**Issue by JawHawk** [JawHawk/Anichinu#2]
When clicked on search icon(with empty searchBox) as marked in image, user gets redirected to ' https://zoro.to/watch/rent-a-girlfriend-2nd-season-15758?ep=92568 ' , but user should be redirected to https://zoro.to/home. 
![5](https://user-images.githubusercontent.com/86140365/193593718-aa76ca68-7de6-42eb-b30b-344a2255cd89.PNG)

**Comment by Akshay9607** [comment]
hey can i work on this issue please

**Comment by JawHawk** [comment]
Sure @Akshay9607

**Comment by sumit-022** [comment]
Please assign me this. I can do it

**Comment by omthakare16** [comment]
I can work on this, assign me !

**Comment by JawHawk** [comment]
I am assigning both @sumit-022 & @omthakare16 . Also one little add on - if the user searches wrong anime name in the Searchbox which isn't in the json data file, just alert (' Choose from the options below or write correct anime name ') .

**Comment by omthakare16** [comment]
Hey ,
This issue is fixed under PR #3 
You may close this issue now.

**Comment by JawHawk** [comment]
@omthakare16  Nice
